### ISSUE TITLE
../zip.c:22:18: fatal error: zlib.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by piaoxuebingfeng** [hsinyuwang/X-Boy#1]
按照 readme.md 在编译 gpsp 二进制程序的时候，遇到如下报错。

../zip.c:22:18: fatal error: zlib.h: 没有那个文件或目录
 #include <zlib.h>
                  ^
compilation terminated.

**Comment by hsinyuwang** [comment]
buildroot 里面得勾选上
