### ISSUE TITLE
PCB-Design fork for a portable audio player possible / interesting?

### ISSUE THREAD

**Issue by sandreas** [hsinyuwang/X-Boy#2]
Hey @hsinyuwang,

I stumbled over your open source pcb design and firmware for the X-Boy-Plus [while discussing a portable audio player design in the rockbox forum.](https://forums.rockbox.org/index.php/topic,54269.120.html)

I think, that with your design and hardware selection with some small modifications it could be possible to design a high quality DIY audio player similar to the good old iPods. I think that there could be a bunch of interested people over at rockbox, especially seeking for a mandarin speaking specialist to negotiate a professional case for such a player.

If you finished your project or are generally interested in this topic, I would love to see this happening. 

Android devices are just too power hungry and big ;)

What do you think?

Best,

sandreas

**Comment by hsinyuwang** [comment]
抱歉，虽然修改硬件对我来说并不难，但制作音乐播放器不是我的主要工作

**Comment by sandreas** [comment]
> 抱歉，虽然修改硬件对我来说并不难，但制作音乐播放器不是我的主要工作

> auto tranlation: Sorry, although modifying hardware is not difficult for me, making music players is not my main purpose


Never mind, I'm glad you responded. If you ever change your mind about this, I would love to support you or even buy your product.

If you don't already know, maybe you can get inspired by the `FunKey S`, which is completely open hard- and firmware:
- Hardware repo (schematics, etc.): https://github.com/FunKey-Project/FunKey-S-Hardware 
- Hardware reference (decision process, explanation): https://doc.funkey-project.com/developer_guide/hardware_reference/
- Firmware (buildroot): https://github.com/DrUm78/FunKey-OS
