### ISSUE TITLE
Linux source code

### ISSUE THREAD

**Issue by AndreRenaud** [hsinyuwang/X-Boy#3]
Hi,
I'm quite interested in this platform, and have been trying to look into it a bit more. Is there any chance you have a git tree of the Linux kernel you're using? I saw some of the stuff that you posted to https://bbs.aw-ol.com/topic/3750/t113-tina-linux-适配-ili9488-屏幕-i80-16bit, but I couldn't find `ili9488_cpu.h`.

This project looks very impressive.

Thanks,
Andre

**Comment by hsinyuwang** [comment]
这很简单，你可以参考st7789v_cpu.h，只需要把st7789v替换成ili9488即可
This is very simple, you can refer to st7789v_cpu.h, just replace st7789v with ili9488
